-- MySQL Script generated by MySQL Workbench
-- Fri Dec 11 15:07:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trojan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trojan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trojan` DEFAULT CHARACTER SET utf8 ;
USE `trojan` ;

-- -----------------------------------------------------
-- Table `trojan`.`jogador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trojan`.`jogador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `hash` VARCHAR(100) NOT NULL,
  `salt` VARCHAR(50) NOT NULL,
  `coins` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trojan`.`mapas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trojan`.`mapas` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `preco` INT NOT NULL,
  PRIMARY KEY (`id_mapa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trojan`.`score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trojan`.`score` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `score` INT NOT NULL,
  `idJogador` INT NOT NULL,
  `idMapa` INT NOT NULL,
  PRIMARY KEY (`idScore`, `idJogador`, `idMapa`),
  INDEX `fk_score_jogador_idx` (`idJogador` ASC),
  INDEX `fk_score_mapas_idx` (`idMapa` ASC),
  CONSTRAINT `fk_score_jogador`
    FOREIGN KEY (`idJogador`)
    REFERENCES `trojan`.`jogador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_score_mapas1`
    FOREIGN KEY (`idMapa`)
    REFERENCES `trojan`.`mapas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

delimiter $
create definer='root'@'localhost' procedure comprar_mapa2(in jogador int, in mapa int, out feito boolean)
begin

declare montante int;
declare custo int; 

start transaction;

set montante = null;
select coins into montante from jogador where id_jogador = jogador;

set custo = null;
select preco into custo from mapas where id_mapa = mapa; 

if montante is null or montante < custo then
rollback;
set feito = false;
else
update jogador
set coins = montante - custo
where id_jogador = jogador;
commit;
set feito = true;
end if;
end $
